### ISSUE TITLE
Give the possibility to disable the side-by-side when editing an entry in the LineEditableDataTable

### ISSUE THREAD

**Issue by yanisaissani** [CharlesCoqueret/ghost-design-system#29]
in the title

**Comment by CharlesCoqueret** [comment]
Target 1.2.0

Show changes is now disabled by default, and can be enabled through this prop: https://github.com/CharlesCoqueret/ghost-design-system/blob/next/src/Components/Organisms/DataTable/Common/types.ts#L237

**Comment by CharlesCoqueret** [comment]
Has been released: https://www.npmjs.com/package/ghost-design-system
