### ISSUE TITLE
Add a new column type to allow dynamic search field in the editable modal in the LineEditableDataTable

### ISSUE THREAD

**Issue by yanisaissani** [CharlesCoqueret/ghost-design-system#30]
The column could be displayed in the table as text ?

**Comment by CharlesCoqueret** [comment]
Target v1.2.0

New column type: https://github.com/CharlesCoqueret/ghost-design-system/blob/next/src/Components/Organisms/DataTable/Common/types.ts#L131

**Comment by CharlesCoqueret** [comment]
Has been released: https://www.npmjs.com/package/ghost-design-system
