### ISSUE TITLE
Add the possibility to add a "hidden" column to be displayed and editable in the modal in the LineEditableDataTable

### ISSUE THREAD

**Issue by yanisaissani** [CharlesCoqueret/ghost-design-system#31]
in the title

**Comment by CharlesCoqueret** [comment]
Target v1.2.0

Open is https://github.com/CharlesCoqueret/ghost-design-system/blob/next/src/Components/Organisms/DataTable/Common/types.ts#L55

**Comment by CharlesCoqueret** [comment]
Has been released: https://www.npmjs.com/package/ghost-design-system
