### ISSUE TITLE
Add options to the generated "Actions" column in the LineEditableDataTable 

### ISSUE THREAD

**Issue by yanisaissani** [CharlesCoqueret/ghost-design-system#33]
Just as the "Actions" column defined for the StaticDataTable, add options (e.g width, title, ...) to the LineEditableDataTable
That would be awesome :D

**Comment by CharlesCoqueret** [comment]
Target 1.2.0

Title can be set here: https://github.com/CharlesCoqueret/ghost-design-system/blob/next/src/Components/Organisms/DataTable/Common/types.ts#L279

Column width can be set here: https://github.com/CharlesCoqueret/ghost-design-system/blob/next/src/Components/Organisms/DataTable/Common/types.ts#L233

**Comment by CharlesCoqueret** [comment]
Has been released: https://www.npmjs.com/package/ghost-design-system
