### ISSUE TITLE
Review 1

### ISSUE THREAD

**Issue by yanisaissani** [CharlesCoqueret/ghost-design-system#44]
- Col span to adapt with hidden columns
- Hide certain columns/fields in the form modal
- Add a modal size prop (idea: small modal by default, large when side by side) (overridable?)
- in IExtraLineEditableDataTableProps, in localization, change modalTitle type from string to (row, rowIndex) => string;
- Tryto make validation work with Yup:v0.26.10

**Comment by CharlesCoqueret** [comment]
- yup@0.26.10 is suffering from 2 critical vulnerabilities and 2 major vulnerabilities, it should no longer be used in new packages. yup@0.30.0 no longer has these vulnerabilities.

**Comment by CharlesCoqueret** [comment]
Fixed in [1.3.0-next.0](https://www.npmjs.com/package/ghost-design-system/v/1.3.0-next.0)
